/// <reference types="astro/client" />
/// <reference path="../worker-configuration.d.ts" />

// Worker bindings (JOURNAL, ASSETS, secrets) are reached through the
// `cloudflare:workers` module rather than Astro.locals — see src/lib/cache.ts.
// The `Env` interface behind them is generated by `wrangler types` from
// wrangler.jsonc; re-run that command after changing bindings.
